# Generated by Django 5.0.6 on 2024-05-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristics', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200, verbose_name='Код (номенклатурный номер)')),
                ('code_okei', models.CharField(max_length=200)),
                ('count_name', models.CharField(max_length=200, verbose_name='Наименование количества')),
                ('price', models.CharField(max_length=200, verbose_name='Стоимость единицы (руб.)')),
                ('inventory_num', models.CharField(max_length=200, verbose_name='Инвентарный номер')),
                ('pasport', models.CharField(max_length=200, verbose_name='паспорт')),
                ('fact_count', models.CharField(max_length=200, verbose_name='Фактическое кол-во')),
                ('fact_sum', models.CharField(max_length=200)),
                ('accounting_count', models.CharField(max_length=200, verbose_name='Кол-во по бух. учету')),
                ('accounting_sum', models.CharField(max_length=200)),
            ],
        ),
    ]
