# Generated by Django 5.0.6 on 2024-05-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='account',
            field=models.FloatField(default=1, verbose_name='Счёт, субсчёт'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='accounting_sum',
            field=models.CharField(max_length=200, verbose_name='По бух. сумма'),
        ),
        migrations.AlterField(
            model_name='device',
            name='characteristics',
            field=models.CharField(max_length=200, verbose_name='Характеристика объект (вид, сорт,группа)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='code_okei',
            field=models.CharField(max_length=200, verbose_name='Код по ОКЕИ'),
        ),
        migrations.AlterField(
            model_name='device',
            name='fact_sum',
            field=models.CharField(max_length=20, verbose_name='Фактическая сумма'),
        ),
        migrations.AlterField(
            model_name='device',
            name='pasport',
            field=models.CharField(max_length=200, verbose_name='Паспорт'),
        ),
        migrations.AlterField(
            model_name='device',
            name='price',
            field=models.CharField(max_length=200, verbose_name='Стоимость единицы (цена)'),
        ),
    ]
